### ISSUE TITLE
Generate nand works only with smaller images

### ISSUE THREAD

**Issue by zoe-vb** [devos50/generate-ipod-touch-1g-nand#5]
Is there a way to modify generate_nand.c for say an 8GB image? 

In the code there is this section: 

#define BANKS 8
#define BLOCKS_PER_BANK 4096
#define PAGES_PER_BANK 524288
#define BYTES_PER_PAGE 2048
#define PAGES_PER_SUBLOCK 1024
#define PAGES_PER_BLOCK 128
#define BYTES_PER_SPARE 64
#define FIL_ID 0x43303032
#define FTL_CTX_VBLK_IND 0

I was wondering what those values would need to be changed to?

**Comment by devos50** [comment]
I thought that the original iPod Touch 1G had a 8GB flash NAND, and that should also be the one that I'm using. Regarding these variables, I think I extracted the right values from iBoot and the kernel and their values are used by the FTL/VFL intermediate NAND layers. Changing one variable might cause some surprises as they are all somewhat related to each other.

For the iPod Touch 2G, I noticed that I had to set some different values. For example, that device has 4KB pages instead of 2KB pages.

**Comment by zoe-vb** [comment]
Interesting, I did a hdiutil -resize 8G on the filesystem-writeable dmg and made it an 8G rootfs and then when I tried to create the nand it failed to actually make a nand folder that functioned correctly and the root wouldn't mount in iBoot.

**Comment by zoe-vb** [comment]
also out of interest could you please supply your launchctl script for loading bash?

**Comment by devos50** [comment]
IIRC, that script was very basic and I mostly copied its structure from the other launchctl scripts. I will have to check if I still have the file somewhere around on my computer though as I might have removed it after it didn't work (I really didn't spend much time on getting bash functional 😅 ).

**Comment by zoe-vb** [comment]
Thanks, if you could share the script I'll attempt to get bash up and running as well, the main issue is that bash needs to work with the serial console. After a lot of searching I have a copy of bash for iOS 1.1 extracted from iLiberty+ so after bash is up and running I'll attempt to jailbreak the emulator!

**Comment by devos50** [comment]
Oh wow that's pretty cool! I remember I got a bus error when trying to execute bash, so it probably has something to do with the serial interface indeed. I didn't dig much into this though as at that time, I was still trying to understand how binaries are exactly loaded and executed. Bash is definitely something that would be extremely helpful for debugging purposes 😀 .

**Comment by zoe-vb** [comment]
When the iPod touch 2 is running it will be 100% possible to jailbreak it if you have indeed managed to get the entire bootchain to function, right now I can execute bash via launchd but there is no console output which I'm trying to figure out now.

**Comment by devos50** [comment]
I have the entire bootchain (bootrom -> LLB -> iBoot -> kernel) functional, but what would be the benefit of jailbreaking the emulator? I already have full control over everything. Do you have a particular use case in mind?

Also, as far as I know, jailbreaking is usually done in DFU mode over USB, both of which I haven't got working yet.

I really hope that I can wrap up the NAND logic tonight when I get home. Before, I used some ugly hacks (read: patch assembly code) to circumvent some nasty internals of the NAND. Unfortunately, that didn't work for loading the `launchd` executable. But I'm very close to doing it the proper way!

**Comment by zoe-vb** [comment]
Some people would want to install tweaks etc or old applications which require a jailbreak. The reason DFU was previously used was so a ramdisk could be booted to modify the root filesystem (change it to rw and copy a loader app) and migrate files to /var which used to be a separate partition, however we don't need a /var partition as we have it on the rootfs. Since we have complete access already to the rootfs we don't need DFU and can make all changes in Finder. However any boot chain patches can be applied also since we now have a full chain emulated.

**Comment by zoe-vb** [comment]
Installer is up and running!!! (time to get the terminal running and you'll have bash) (also I really need to know where you got your iboot from and how you decrypted it)

<img width="1792" alt="Screenshot 2023-07-19 at 17 27 21" src="https://github.com/devos50/generate-ipod-touch-1g-nand/assets/96234996/914cd440-91f0-4031-b2e8-5f15bc1cdd8e">

**Comment by devos50** [comment]
That's great work!

Regarding the iBoot - isn't the binary included in the IPSW encrypted with the 8900 protocol? If so, you should be able to decrypt it with any 8900 decryptor. AFAIK I didn't make patches in iBoot.

**Comment by zoe-vb** [comment]
I used 8900decrypter which decrypted everything else just fine. The iBoot image is also decrypted but when I use diff between the iboot you provide and the one in the ipsw there are many differences and qemu hangs on a black screen and iBoot doesn't even execute

**Comment by devos50** [comment]
I just looked into this, and I think I understand how it works.

The iBoot included in the IPSW is indeed encrypted, and after decryption, you end up with an executable (Mach-O ELF) file. In a normal boot sequence, LLB will place the parts of this executable at the correct locations in memory, but as I didn't have LLB up and running, I would have to do this by myself in QEMU. Just trying to run this binary is not going to work. In fact, there is another iOS emulator that also "unzips" the executable manually using some Mach-O library.

Now that didn't really work out well for me. So I think I loaded the full binary into memory, and then I dumped all the memory related to executable section. The resulting file is the file I included in the QEMU-iOS repository. That's why it differs from the binary you get after 8900 decryption.

Unfortunately, I don't really remember the exact details of this process, but it should be doable to replicate as the Mach-O format is very well-documented 👍

**Comment by zoe-vb** [comment]
Figured it out; will add it to the documentation (probably will create a wiki at this point). The decrypted iBoot is actually a container which holds a mach-o called ibot, which is the raw binary that is executed by qemu! I used Ghidra to load the iBoot then to open ibot and then the memory map function to dump the contents of memory.

**Comment by devos50** [comment]
Ah thanks for clarifying, I might have used Ghidra indeed to do this stuff 😂

**Comment by zoe-vb** [comment]
It was genuinely a last ditch attempt 😂 I couldn't understand why everything was saying that the iboot file wasn't mach-o and then when I opened it in Ghidra I practically kicked myself
