### ISSUE TITLE
Can the process be reversed to get the image back again?

### ISSUE THREAD

**Issue by zoe-vb** [devos50/generate-ipod-touch-1g-nand#7]
So there was a tool I needed to run to patch springboard and the only way to do it was through iOS so is there a way to convert all the pages back into filesystem-readonly.img?

**Comment by devos50** [comment]
Hmm yes I think this should be possible. But note that the current version of the emulator doesn't support file persistence (I haven't gotten the write commands to work as it did seem to mess up the VFL/FTL context pages). But this shouldn't really be an issue for running the emulator since these changes are also buffered by VFS AFAIK.

**Comment by zoe-vb** [comment]
Okay thanks, I made a script in /bin and a LaunchDaemon which executes on boot of the emulator and patches springboard and then restarts it which works just fine instead. I'm going to patch the binary on my own iPod Touch and then create a diff with bsdiff and upload it to my fork of the generate-nand repo so others can replicate my procedure.
